platform.name=Android
appium.server.url=http://127.0.0.1:4723
app.commandTimeout=60

chromedriver.path=
web.browser.name=chrome

app.useEmulator=true
enable.console.colors=true

android.app.path=apps/android/Swaglabs.apk
android.app.package.name=com.swaglabsmobileapp
android.app.activity.name=com.swaglabsmobileapp.SplashActivity
android.app.wait.activity=com.swaglabsmobileapp.MainActivity
android.adb.path=D:/Android/Sdk/platform-tools/adb.exe
ios.app.path=apps/ios/
ios.app.package.name=io.appium.android.apis
ios.app.activity.name=io.appium.android.apis.ApiDemos


android.device.name=pixel_6a
android.automation.name=UiAutomator2
android.device.udid=emulator-5554
android.avd.name=Pixel_6a
android.avdLaunchTimeout=280
android.avdReadyTimeout=220
android.uiautomator2ServerLaunchTimeout=60
android.uiautomator2ServerInstallTimeout=60
android.deviceReadyTimeout=120
ios.device.name=pixel_6a
ios.automation.name=UiAutomator2
ios.device.udid=emulator-5554
ios.avd.name=Pixel_6a

real.device.name=Real_Device
android.real.device.udid=d20a727a
ios.real.device.udid=d20a727a

maintaince.timeout=5