# App Details
app.path=apps/android/AppDemos.apk
app.package.name = io.appium.android.apis
app.activity.name = io.appium.android.apis.ApiDemos

# Device Details
device.name=pixel_6a
platform.name=Android
automation.name=UiAutomator2
device.udid=emulator-5554

# Appium Server Details
appium.server.url=http://127.0.0.1:4723

# Real Device Details
real.device.name=Real_Device
real.device.udid=d20a727a

#avd details
avd.name=Pixel_6a
++
# Test Settings
implicit.wait=10
explicit.wait=20